apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: multi-node
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: C:/Users/nguyenqh/training/java/demo-communication/data/data-ctrlplane
        containerPath: /mnt/data
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 50051
        hostPort: 50051
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: C:/Users/nguyenqh/training/java/demo-communication/data/data-worker-1
        containerPath: /mnt/data
#    extraPortMappings:
#      - containerPort: 80
#        hostPort: 11080
#        listenAddress: 127.0.0.1
#        protocol: TCP
#      - containerPort: 443
#        hostPort: 11443
#        listenAddress: 127.0.0.1
#        protocol: TCP
#      - containerPort: 9090
#        hostPort: 11090
#        listenAddress: 127.0.0.1
#        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: C:/Users/nguyenqh/training/java/demo-communication/data/data-worker-2
        containerPath: /mnt/data
#    extraPortMappings:
#      - containerPort: 80
#        hostPort: 12080
#        listenAddress: 0.0.0.0
#        protocol: TCP
#      - containerPort: 443
#        hostPort: 12443
#        listenAddress: 127.0.0.1
#        protocol: TCP
#      - containerPort: 9090
#        hostPort: 12090
#        listenAddress: 0.0.0.0
#        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: C:/Users/nguyenqh/training/java/demo-communication/data/data-worker-3
        containerPath: /mnt/data
#    extraPortMappings:
#      - containerPort: 80
#        hostPort: 13080
##        listenAddress: 0.0.0.0
#        protocol: TCP
#      - containerPort: 443
#        hostPort: 13443
##        listenAddress: 127.0.0.1
#        protocol: TCP
#      - containerPort: 9090
#        hostPort: 13090
##        listenAddress: 0.0.0.0
#        protocol: TCP
networking:
  ipFamily: dual # ipv6
  apiServerAddress: 127.0.0.1
  apiServerPort: 56443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
#featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
#  "CSIMigration": true
