apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demo-communication
  name: rs-pv
  labels:
    app: rs-pv
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes: [ ReadWriteMany ]
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  local:
    path: /mnt/data
  nodeAffinity:
     required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values: ["multi-node-control-plane", "multi-node-worker", "multi-node-worker2", "multi-node-worker3"]
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: demo-communication
#  name: demo-comm-pv
#  labels:
#    app: demo-comm-pv
#spec:
#  storageClassName: standard
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  capacity:
#    storage: 2Gi
#  hostPath:
#    path: /Users/hiepnq/Working/training/java/demo-communication/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-communication
  name: rs-pvc
  labels:
    app: rs-pvc
spec:
  storageClassName: local-storage
#  volumeName: demo-comm-pv
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 1Gi
