apiVersion: v1
kind: Service
metadata:
  name: demo-comm-svc
  labels:
    app: demo-comm-svc
spec:
  selector:
    app: demo-comm-con
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
  