apiVersion: v1
kind: Service
metadata:
  namespace: demo-communication
  name: demo-comm-svc
  labels:
    app: demo-comm-svc
spec:
  selector:
    app: demo-comm-con
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  type: ClusterIP
  