apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-comm-pv
  labels:
    app: demo-comm-pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  local:
    path: /run/desktop/mnt/host/c/Users/nguyenqh/training/java/demo-communication/data
  nodeAffinity:
     required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
                 - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-comm-pvc
spec:
  storageClassName: standard
  volumeName: demo-comm-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
