apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demo-communication
  name: test-pv
  labels:
    app: test-pv
spec:
  storageClassName: local-storage
  #  storageClassName: fast-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
#  hostPath:
#    path: "/Users/hiepnq/Working/training/java/demo-communication/data"
  local:
    path: "/Users/hiepnq/Working/training/java/demo-communication/data"
#    fsType: "ext4"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
#            - { key: kubernetes.io/hostname, operator: NotIn, values: [ "" ] }
            # kubectl describe node
#            - { key: kubernetes.io/hostname, operator: In, values: [ "kind-local-cluster", "harryng-mbp", "docker-desktop", "local-cluster-control-plane" ]}
          - { key: kubernetes.io/hostname, operator: In, values: [ "local-cluster-control-plane", "kind-local-cluster", "harryng-mbp", "docker-desktop" ]}
#          - { key: kubernetes.io/hostname, operator: In, values: [ "docker-desktop" ] }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-communication
  name: test-pvc
  labels:
    app: test-pvc
spec:
#  volumeName: test-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
#  storageClassName: fast-storage
#  storageClassName: local-path
---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo-communication
  name: busybox-volume-test
  labels:
    app: busybox-volume-test
spec:
  containers:
    - name: busybox
      image: busybox
      env:
        - { name: "TZ", value: "Asia/Ho_Chi_Minh" }
      #      command: ["tail", "-f", "/dev/null"]
      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
      volumeMounts:
        - name: test-volume
          mountPath: /mnt/data
  volumes:
    - name: test-volume
#      hostPath:
#        path: "/Users/hiepnq/Working/training/java/demo-communication/data"
#        type: Directory
      persistentVolumeClaim:
        claimName: test-pvc
