apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demo-communication
  name: test-pv
#spec:
#  capacity:
#    storage: 1Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: standard
#  hostPath:
#    path: /Users/hiepnq/Working/training/java/demo-communication/data
spec:
  storageClassName: standard
#  storageClassName: hostpath
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
#  hostPath:
#    path: /Users/hiepnq/Working/training/java/demo-communication/data
  local:
    path: /Users/hiepnq/Working/training/java/demo-communication/data
  nodeAffinity:
     required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
                 - docker-desktop   # same as node name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-communication
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
#  storageClassName: hostpath
---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo-communication
  name: busybox-volume-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: test-volume
          mountPath: /mnt/data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
