apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demo-communication
  name: test-db-pv
  labels:
    app: test-db-pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  local:
    path: /Users/hiepnq/Working/training/java/demo-communication/data/db/data
  nodeAffinity:
     required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
                 - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-communication
  name: test-db-pvc
spec:
  storageClassName: standard
  volumeName: test-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
