version: "3.8"
services:
  proxy:
#    build: ./nginx
    image: nginx:latest
    container_name: proxy
    hostname: proxy
    domainname: proxy
    read_only: true
    env_file:
      - ./docker-compose-mac.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - /private/etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
      - /Volumes/WORKING/training/docker/demo-communication/tmp:/tmp
      - /Volumes/WORKING/training/docker/demo-communication/proxy/cache:/var/cache/nginx
      - /Volumes/WORKING/training/docker/demo-communication/proxy/run:/var/run
      - /Volumes/WORKING/training/docker/demo-communication/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /Volumes/WORKING/training/docker/demo-communication/proxy/log/nginx:/var/log/nginx
      - /Volumes/WORKING/training/docker/demo-communication/proxy/cert:/etc/nginx/cert
    networks:
      dmz-net:
        ipv4_address: "172.16.238.2"
        ipv6_address: "2001:3984:3989::2"
      external-net:
  app:
    # build: ./app
    image: openjdk:11.0.7-jdk
    container_name: demo-app
    read_only: true
    hostname: demo-app
    domainname: demo-app
    env_file:
      - ./docker-compose-mac.env
    environment:
      DEMO_HOME: /opt/demo-communication
#    ports:
#      - 9090:9090
    volumes:
#      - /private/etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
      - /Volumes/WORKING/training/docker/demo-communication/tmp:/tmp
      - /Volumes/WORKING/training/docker/demo-communication/app/opt:/opt/demo-communication
    depends_on:
      - proxy
    networks:
      internal-net:
        ipv4_address: "172.16.239.10"
        ipv6_address: "2001:3984:3990::10"
      dmz-net:
        aliases:
          - demo-app
        ipv4_address: "172.16.238.10"
        ipv6_address: "2001:3984:3989::10"
    command: java -jar /opt/demo-communication/demo-communication-web-1.0-SNAPSHOT.war
networks:
  internal-net:
#    driver: bridge
    internal: true
    name: internal-net
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
        - subnet: "2001:3984:3990::/64"
  dmz-net:
#    driver: bridge
    internal: true
#    enable_ipv6: true
    name: dmz-net
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
#        gateway: "172.16.238.1"
        - subnet: "2001:3984:3989::/64"
#        gateway: "2001:3984:3989::1"
  external-net:
    name: external-net