version: "3.8"
services:
  proxy:
#    build: ./nginx
    image: ${nginxImg}
    container_name: proxy
    read_only: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${TMP_DIR}:/tmp
      - ${PROXY_DIR}/cache:/var/cache/nginx
      - ${PROXY_DIR}/run:/var/run
      - ${PROXY_DIR}/nginx.conf:/etc/nginx/nginx.conf
#      - ${PROXY_DIR}/log:/var/log
      - ${PROXY_DIR}/log/nginx:/var/log/nginx
      - ${PROXY_DIR}/cert:/etc/nginx/cert
#    links:
#      - "app"
#    network_mode: bridge
    networks:
      demo-bridge:
        ipv4_address: "172.16.238.2"
        ipv6_address: "2001:3984:3989::2"
      external-net:
  #demo-communication
  app:
    # build: ./app
    image: ${openjdkImg}
    container_name: demo-comm
    read_only: true
    environment:
      DEMO_HOME: ${DEMO_HOME}
#    ports:
#      - 9090:9090
    volumes:
      - ${TMP_DIR}:/tmp
      - ${APP_DIR}/opt:/opt/demo-communication
    depends_on:
      - proxy
#    network_mode: bridge
    networks:
      demo-bridge:
        ipv4_address: "172.16.238.10"
        ipv6_address: "2001:3984:3989::10"
    command: java -jar ${DEMO_HOME}/demo-communication-web-1.0-SNAPSHOT.war
networks:
  demo-bridge:
    driver: bridge
    internal: true
#    enable_ipv6: true
    name: demo-bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
#        gateway: "172.16.238.1"
        - subnet: "2001:3984:3989::/64"
#        gateway: "2001:3984:3989::1"
  external-net:
#    driver: host
#    external: true
    name: external-net