version: "3.8"
services:
  proxy:
#    build: ./nginx
    image: nginx
    container_name: proxy
    read_only: true
    ports:
      - 80:80
    volumes:
      - /docker/tmp:/tmp
      - /docker/nginx/cache:/var/cache/nginx
      - /docker/nginx/run:/var/run
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/log:/var/log
      - /docker/nginx/cert:/etc/nginx/cert
#    links:
#      - "app"
#    network_mode: bridge
    networks:
      demo-bridge:
        ipv4_address: "172.16.238.2"
        ipv6_address: "2001:3984:3989::2"
#      external-net:
  #demo-communication
  app:
    # build: .
    image: openjdk
    container_name: demo-comm
    read_only: true
    environment:
      DEMO_HOME: ${DEMO_HOME}
#    ports:
#      - 9090:9090
    volumes:
      - /docker/tmp:/tmp
      - /docker/demo-communication/opt:/opt/demo-communication
    depends_on:
      - proxy
#    network_mode: bridge
    networks:
      demo-bridge:
        ipv4_address: "172.16.238.10"
        ipv6_address: "2001:3984:3989::10"
    command: java -jar ${DEMO_HOME}/demo-communication-web-1.0-SNAPSHOT.war
networks:
  demo-bridge:
    driver: bridge
    internal: true
#    enable_ipv6: true
    name: demo-bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
#        gateway: "172.16.238.1"
        - subnet: "2001:3984:3989::/64"
#        gateway: "2001:3984:3989::1"
#  external-net:
#    driver: bridge
#    external: true
#    name: external-net