---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo-communication
  name: busybox-volume-test
  labels:
    app: busybox-volume-test
spec:
  containers:
    - name: busybox
      image: busybox
      env:
        - { name: "TZ", value: "Asia/Ho_Chi_Minh" }
#      command: ["tail", "-f", "/dev/null"]
      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
      volumeMounts:
        - name: test-volume
          mountPath: /mnt/data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  namespace: demo-communication
#  name: alpine-volume-test
#  labels:
#    app: alpine-volume-test
#spec:
#  containers:
#    - name: alpine
#      image: alpine:edge
#      env:
#        - { name: "TZ", value: "Asia/Ho_Chi_Minh" }
#      #      command: ["tail", "-f", "/dev/null"]
#      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
##      volumeMounts:
##        - name: test-volume
##          mountPath: /mnt/data
##  volumes:
##    - name: test-volume
##      persistentVolumeClaim:
##        claimName: test-pvc
