logging:
  level:
    root: info
  file:
    path: ~/app-log/demo-communication/log

# server
server:
  error:
    whitelabel:
      enabled: false

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: false
#    shutdown:
#      enabled: false
# config
test-array:
  - id1
  - id2
spring:
  thymeleaf:
    cache: true