logging:
  file:
    name: demo-communication-ws
    path: ./data/log
#  file:
#    path: ./log

# server
#server:
#  error:
#    whitelabel:
#      enabled: true

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#    shutdown:
#      enabled: true

# config

#spring:
#  thymeleaf:
#    cache: false
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
#      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, \
#      org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration, \
#      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  docker:
#    compose:
#      enabled: true
#      host: ./docker/docker-compose-dev.xml
