logging:
  level:
    root: info

# server
#server:
#  error:
#    whitelabel:
#      enabled: false

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: false
#    shutdown:
#      enabled: false
# config
#spring:
#  thymeleaf:
#    cache: true