logging:
  level:
    root: info

# server
server:
  error:
    whitelabel:
      enabled: true
# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#    shutdown:
#      enabled: true

# config

spring:
  thymeleaf:
    cache: false
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
#      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, \
#      org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration, \
#      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  docker:
#    compose:
#      enabled: true
#      host: ./docker/docker-compose-dev.xml
  datasource:
    url: jdbc:sqlserver://local-ext-svc.demo-communication.svc.cluster.local:1433;databaseName=test_db;integratedSecurity=false;\
      encrypt=false;trustServerCertificate=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
  transaction:
    rollback-on-commit-failure: true