logging:
  level:
    root: info
  file:
    path: ./log

# server
server:
  error:
    whitelabel:
      enabled: true

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#    shutdown:
#      enabled: true

# config

spring:
  thymeleaf:
    cache: false
  docker:
    compose:
      enabled: true
      host: docker-compose-dev.xml
