# logging
logging:
  config: "classpath:logback.xml"
#  file:
#    name: demo-communication-web_${POD_NAME:''}.log
#    path: /opt/log

# server
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /web
  error:
    whitelabel:
      enabled: false
# spring:
spring:
#  jackson:
#    date-format: "yyyy-MM-dd'T'HH:mm:ss"
#    serialization:
#      write-dates-as-timestamps: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: templates/pages/
      suffix: .html
#    format:
#      date-time: iso
#      time: iso
#      date: iso
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
#      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, \
#      org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration, \
#      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, \
#      org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 0
      max-total: 1
      max-idle: 1
      min-idle: 0
  profiles:
    active: "${env != null? env:'dev'}"
  threads:
    virtual:
      enabled: true
  thymeleaf:
    cache: true
    prefix: templates/pages/
    suffix: .html

# grpc server
grpc:
  server:
    port: 50051

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#    shutdown:
#      enabled: true
