logging:
  level:
    root: info

# server
server:
  error:
    whitelabel:
      enabled: false

# management:
#management:
#  server:
#    port: 9090
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: false
#    shutdown:
#      enabled: false
# config
test-array:
  - id1
  - id2
spring:
  thymeleaf:
    cache: true

#db:
#  driver: "org.postgresql.Driver"
#  url: "jdbc:postgresql://localhost:5432/test_db"
#  username: test_db
#  password: test_db
#  minPoolSize: 1
#  maxPoolSize: 3
#  dialect: "org.hibernate.dialect.PostgreSQLDialect"
