-- db test_db
create table AUTH_USER(
	ID_ INTEGER not null primary key,
	USERNAME VARCHAR(70) unique,
	PASSWD VARCHAR(140),
	SCREENNAME VARCHAR(70),
	DOB TIMESTAMP,
	PASSWD_ENC_METHOD VARCHAR(70),
	CREATED_DATE TIMESTAMP,
	MODIFIED_DATE TIMESTAMP,
	STATUS VARCHAR(35)
);

